spring.application.name=BackEnd-AngularDemo
server.port=8082
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:AppDB
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true

